name: Publish Docker image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to Tencent Registry
      uses: docker/login-action@v1
      with:
        registry: ccr.ccs.tencentyun.com
        username: ${{ secrets.TCR_USER }}
        password: ${{ secrets.TCR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/prompt-generator:latest

    - name: Build and push Docker image to Tencent Registry
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: ccr.ccs.tencentyun.com/saijun/prompt-generator:latest
